//! Schéma versionné, appliqué automatiquement à l'ouverture d'un coffre.

use rusqlite_migration::{M, Migrations};

#[must_use]
#[allow(clippy::too_many_lines)] // le registre grandit d'une paire par migration
pub fn migrations() -> Migrations<'static> {
    Migrations::new(vec![
        M::up(include_str!("migrations/0001_init_up.sql"))
            .down(include_str!("migrations/0001_init_down.sql")),
        M::up(include_str!("migrations/0002_app_layer_up.sql"))
            .down(include_str!("migrations/0002_app_layer_down.sql")),
        M::up(include_str!("migrations/0003_prospection_up.sql"))
            .down(include_str!("migrations/0003_prospection_down.sql")),
        M::up(include_str!("migrations/0004_billing_up.sql"))
            .down(include_str!("migrations/0004_billing_down.sql")),
        M::up(include_str!("migrations/0005_quotes_up.sql"))
            .down(include_str!("migrations/0005_quotes_down.sql")),
        M::up(include_str!("migrations/0006_company_profile_up.sql"))
            .down(include_str!("migrations/0006_company_profile_down.sql")),
        M::up(include_str!("migrations/0007_expenses_up.sql"))
            .down(include_str!("migrations/0007_expenses_down.sql")),
        M::up(include_str!("migrations/0008_mutability_up.sql"))
            .down(include_str!("migrations/0008_mutability_down.sql")),
        M::up(include_str!(
            "migrations/0009_prospection_mutability_up.sql"
        ))
        .down(include_str!(
            "migrations/0009_prospection_mutability_down.sql"
        )),
        M::up(include_str!("migrations/0010_fiscal_year_up.sql"))
            .down(include_str!("migrations/0010_fiscal_year_down.sql")),
        M::up(include_str!(
            "migrations/0011_fiscal_year_immutability_up.sql"
        ))
        .down(include_str!(
            "migrations/0011_fiscal_year_immutability_down.sql"
        )),
        M::up(include_str!("migrations/0012_mission_lineage_up.sql"))
            .down(include_str!("migrations/0012_mission_lineage_down.sql")),
        M::up(include_str!("migrations/0013_payment_corrections_up.sql"))
            .down(include_str!("migrations/0013_payment_corrections_down.sql")),
        M::up(include_str!("migrations/0014_opening_balance_up.sql"))
            .down(include_str!("migrations/0014_opening_balance_down.sql")),
        M::up(include_str!("migrations/0015_tax_losses_up.sql"))
            .down(include_str!("migrations/0015_tax_losses_down.sql")),
        M::up(include_str!(
            "migrations/0016_expense_reconciliation_up.sql"
        ))
        .down(include_str!(
            "migrations/0016_expense_reconciliation_down.sql"
        )),
        M::up(include_str!("migrations/0017_bank_settlements_up.sql"))
            .down(include_str!("migrations/0017_bank_settlements_down.sql")),
        M::up(include_str!("migrations/0018_bank_fitid_up.sql"))
            .down(include_str!("migrations/0018_bank_fitid_down.sql")),
        M::up(include_str!("migrations/0019_setup_up.sql"))
            .down(include_str!("migrations/0019_setup_down.sql")),
        M::up(include_str!("migrations/0020_opening_references_up.sql"))
            .down(include_str!("migrations/0020_opening_references_down.sql")),
        M::up(include_str!("migrations/0021_compliance_up.sql"))
            .down(include_str!("migrations/0021_compliance_down.sql")),
        M::up(include_str!("migrations/0022_fixed_assets_up.sql"))
            .down(include_str!("migrations/0022_fixed_assets_down.sql")),
        M::up(include_str!("migrations/0023_prospect_party_up.sql"))
            .down(include_str!("migrations/0023_prospect_party_down.sql")),
        M::up(include_str!("migrations/0024_follow_up_up.sql"))
            .down(include_str!("migrations/0024_follow_up_down.sql")),
        M::up(include_str!("migrations/0025_duty_filings_up.sql"))
            .down(include_str!("migrations/0025_duty_filings_down.sql")),
        M::up(include_str!("migrations/0026_vault_started_on_up.sql"))
            .down(include_str!("migrations/0026_vault_started_on_down.sql")),
        M::up(include_str!("migrations/0027_papers_up.sql"))
            .down(include_str!("migrations/0027_papers_down.sql")),
        M::up(include_str!("migrations/0028_vat_carry_in_up.sql"))
            .down(include_str!("migrations/0028_vat_carry_in_down.sql")),
        M::up(include_str!("migrations/0029_vat_refunds_up.sql"))
            .down(include_str!("migrations/0029_vat_refunds_down.sql")),
        M::up(include_str!("migrations/0030_vat_reversals_up.sql"))
            .down(include_str!("migrations/0030_vat_reversals_down.sql")),
        M::up(include_str!("migrations/0031_expense_paid_by_up.sql"))
            .down(include_str!("migrations/0031_expense_paid_by_down.sql")),
        M::up(include_str!("migrations/0032_invoice_origin_up.sql"))
            .down(include_str!("migrations/0032_invoice_origin_down.sql")),
        M::up(include_str!("migrations/0033_invoice_write_offs_up.sql"))
            .down(include_str!("migrations/0033_invoice_write_offs_down.sql")),
        M::up(include_str!("migrations/0034_follow_up_cycle_up.sql"))
            .down(include_str!("migrations/0034_follow_up_cycle_down.sql")),
        M::up(include_str!("migrations/0035_estimation_lines_up.sql"))
            .down(include_str!("migrations/0035_estimation_lines_down.sql")),
        M::up(include_str!("migrations/0036_prospect_phrases_up.sql"))
            .down(include_str!("migrations/0036_prospect_phrases_down.sql")),
        M::up(include_str!("migrations/0037_prospect_series_up.sql"))
            .down(include_str!("migrations/0037_prospect_series_down.sql")),
        M::up(include_str!("migrations/0038_prospect_genres_up.sql"))
            .down(include_str!("migrations/0038_prospect_genres_down.sql")),
        M::up(include_str!("migrations/0039_journal_entries_up.sql"))
            .down(include_str!("migrations/0039_journal_entries_down.sql")),
        M::up(include_str!("migrations/0040_journal_line_aux_up.sql"))
            .down(include_str!("migrations/0040_journal_line_aux_down.sql")),
        M::up(include_str!("migrations/0041_journal_line_label_up.sql"))
            .down(include_str!("migrations/0041_journal_line_label_down.sql")),
        M::up(include_str!("migrations/0042_reverse_charge_up.sql"))
            .down(include_str!("migrations/0042_reverse_charge_down.sql")),
        M::up(include_str!("migrations/0043_dossier_work_notes_up.sql"))
            .down(include_str!("migrations/0043_dossier_work_notes_down.sql")),
        M::up(include_str!("migrations/0044_work_kinds_up.sql"))
            .down(include_str!("migrations/0044_work_kinds_down.sql")),
        M::up(include_str!("migrations/0045_mail_up.sql"))
            .down(include_str!("migrations/0045_mail_down.sql")),
        M::up(include_str!("migrations/0046_mail_signature_up.sql"))
            .down(include_str!("migrations/0046_mail_signature_down.sql")),
        M::up(include_str!("migrations/0047_mail_probe_up.sql"))
            .down(include_str!("migrations/0047_mail_probe_down.sql")),
        M::up(include_str!("migrations/0048_sent_copy_up.sql"))
            .down(include_str!("migrations/0048_sent_copy_down.sql")),
    ])
}
