[package]
name = "freeflow-desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "freeflow-desktop"
path = "src/main.rs"

[dependencies]
axum = "0.8.9"
freeflow-core = { version = "0.1.0", path = "../freeflow-core" }
freeflow-web = { version = "0.1.0", path = "../freeflow-web" }
http = "1.5.0"
http-body-util = "0.1.5"
tauri = { version = "2.11.5", features = [] }
tower = "0.5.3"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
