[package]
name = "griffe-desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "griffe-desktop"
path = "src/main.rs"

[dependencies]
axum = "0.8.9"
griffe-core = { version = "0.3.9", path = "../griffe-core" }
griffe-mail = { version = "0.3.9", path = "../griffe-mail" }
griffe-web = { version = "0.3.9", path = "../griffe-web" }
http = "1.5.0"
http-body-util = "0.1.5"
tauri = { version = "2.11.5", features = [] }
time = { version = "0.3.55", features = ["formatting"] }
tokio = { version = "1.53.1", features = ["rt", "time"] }
tower = "0.5.3"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
