[package]
name = "freeflow-invoice"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
freeflow-core = { version = "0.1.0", path = "../freeflow-core" }
quick-xml = "0.42.0"
tempfile = "3.27.0"
thiserror = "2.0.20"
time = { version = "0.3.55", features = ["formatting"] }

[dev-dependencies]
uuid = { version = "1.26.0", features = ["v7"] }
